{
  "uid" : "551f1039b6b08f99",
  "name" : "Unauthorized device attempts to access the EST endpoint",
  "fullName" : "EST Endpoint for Onboarded Devices: Unauthorized device attempts to access the EST endpoint",
  "historyId" : "3f408db859a4f80e69fc960dbea48a70",
  "time" : {
    "start" : 1746708253440,
    "stop" : 1746708253477,
    "duration" : 37
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: STEP: Given the endpoint is available\n",
  "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_010_r_11_steps.py\", line 19, in step_given_endpoint_available\n    raise AssertionError(msg)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: STEP: Given the endpoint is available\n",
    "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_010_r_11_steps.py\", line 19, in step_given_endpoint_available\n    raise AssertionError(msg)\n",
    "steps" : [ {
      "name" : "Given the EST endpoint is available",
      "time" : {
        "start" : 1746708253442,
        "stop" : 1746708253443,
        "duration" : 1
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: STEP: Given the endpoint is available\n",
      "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_010_r_11_steps.py\", line 19, in step_given_endpoint_available\n    raise AssertionError(msg)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Given a device with invalid credentials",
      "time" : {
        "start" : 1746708253477,
        "stop" : 1746708253477,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When the device sends a EST request",
      "time" : {
        "start" : 1746708253477,
        "stop" : 1746708253477,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then the system should reject the request with an \"Unauthorized\" error",
      "time" : {
        "start" : 1746708253477,
        "stop" : 1746708253477,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "EST Endpoint for Onboarded Devices"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 3,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "9b24e5a37eb6b4b0",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/17/#testresult/9b24e5a37eb6b4b0",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: Given the endpoint is available\n",
        "time" : {
          "start" : 1746705364861,
          "stop" : 1746705364893,
          "duration" : 32
        }
      }, {
        "uid" : "ddee31ff7f0210b5",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/16/#testresult/ddee31ff7f0210b5",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: Given the endpoint is available\n",
        "time" : {
          "start" : 1746616916247,
          "stop" : 1746616916280,
          "duration" : 33
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "551f1039b6b08f99.json",
  "parameterValues" : [ ]
}